site_name: The BackBee documentation
site_url: http://www.backbee.com/
site_description: The BackBee documentation

repo_url: https://github.com/backbee/docs

docs_dir: doc
extra_javascript: ['js/backbee.js']

theme: 'bootstrap'

pages:
    - Introduction: 'index.md'
    - Developper documentation:
        - 'Requirements': 'developper-documentation/requirements.md'
        - 'Installation': 'developper-documentation/installation.md'
        - 'Architecture': 'developper-documentation/architecture.md'
        - 'Configuration': 'developper-documentation/configuration.md'
    - 'Cookbooks':
        - 'Create new commands': 'developper-documentation/cookbooks/create_new_commands.md'
        - 'Customize error pages': 'developper-documentation/cookbooks/customize_error_pages.md'
    - 'Components':
        - 'Config': 'developper-documentation/components/config.md'

copyright: Copyright &copy; 2014-2015, <a href="http://www.backbee.com">BackBee project</a>.
